#!/usr/bin/with-contenv bash

if [ ! -d /mangos/dbc ]; then
        if [ -d /config/wowfiles/dbc ]; then
                ln -s /config/wowfiles/dbc /home/server/wow/data
        fi
fi

if [ ! -d /mangos/mmaps ]; then
        if [ -d /config/wowfiles/mmaps ]; then
                ln -s /config/wowfiles/mmaps /home/server/wow/data
        fi
fi

if [ ! -d /mangos/vmaps ]; then
        if [ -d /config/wowfiles/vmaps ]; then
                ln -s /config/wowfiles/vmaps /home/server/wow/data
        fi
fi

if [ ! -d /mangos/maps ]; then
        if [ -d /config/wowfiles/maps ]; then
                ln -s /config/wowfiles/maps /home/server/wow/data
        fi
fi

if [ ! -d /config/worldlogs ]; then
        mkdir /config/worldlogs/
fi

if [ ! -d /config/authlogs ]; then
        mkdir /config/authlogs/
fi

if [ ! -d /config/wowconfig ]; then
        mkdir /config/wowconfig/
fi

if [ ! -f /config/wowconfig/worldserver.conf ]; then
   cp /install/worldserver.conf /config/wowconfig
fi

if [ ! -f /config/wowconfig/authserver.conf ]; then
   cp /install/authserver.conf /config/wowconfig
fi

test -f /proc/net/if_inet6 && echo "IPv6 supported. Not changing nginx config" || sed -i '\|listen \[::\]:80 default_server;|s///' /etc/nginx/sites-enabled/default
